name: Bedwars
version: '${project.version}'
main: xemii16.ecraft.bedwars.Plugin
api-version: 1.16
authors: [ Xemii16 ]
commands:
  arena:
    aliases:
      - a
  menu:
    aliases:
      - m
  game:
    aliases:
      - g
  team:
    aliases:
      - t
